### ISSUE TITLE
Feature request: Get point symmetry at atomic position

### ISSUE THREAD

**Issue by shyuep** [atztogo/spglib#28]
Right now, spglib provides the Wyckoff symbols and spacegroup. I would like to request that spglib also provide point symmetries for each position, e.g., like what is reported in the international tables. This is extremely useful information when working with properties that depend on site symmetry.

**Comment by atztogo** [comment]
I was thinking it's not necessary because it's easy to implement on user side. But I got a similar request recently, too. So I will consider.

I think it would be OK just returning a set of indices of space group operations corresponding to the site-point symmetry at each atom. A user will collect rotation parts from the selected space group operations, which are the requested site-point symmetry at each atom. How do you think?

**Comment by shyuep** [comment]
Returning just a set of space group operation is a start. But the user usually likes to know what symmetry it is, and it is not easy to simply get that from the operations. For example, many applications want to know if there is inversion symmetry or mirror symmetry at a site.

**Comment by atztogo** [comment]
After the start, this feature is completely separable from spglib so it's not necessary to be a part of spglib. This feature is provided by the Bilbao crystallographic server by the group of M. I. Aroyo and they are really the specialists of crystallography but I am not. Learning crystallographic conventions needs time. It's not an easy job and currently it is difficult for me to find the time for it.

**Comment by atztogo** [comment]
@shyuep , are you still interested in this?

**Comment by atztogo** [comment]
OK. Probably I understand it now. Finding time, I will work to provide them but only for the standard settings.

**Comment by atztogo** [comment]
It seems I am very slow to work on this. I roughly finished this implementation and the code is in develop branch. I hope I will release this someday soon after considering issue #69.

**Comment by atztogo** [comment]
I have released v1.12.0. This version contains the site-symmetry symbols.
https://atztogo.github.io/spglib/dataset.html#site-symmetry-symbols
This feature is currently marked **experimental** just by my feeling because aging by dogfooding is necessary. I think v1.12.x will be the last versions as v1.x, and am working toward v2.0 with some API changes. These API changes will be mainly for the C integer type changes of variables for k-point mesh symmetry, and may not result in large impact to python case hopefully.

**Comment by atztogo** [comment]
I close this issue. Please re-open if you need.
