### ISSUE TITLE
Tests for Wyckoff positions fail on multiple architectures

### ISSUE THREAD

**Issue by merkys** [atztogo/spglib#69]
While building spglib v1.11.2 for Debian, I noticed failures of ``test_get_symmetry_dataset`` on [arm64](https://buildd.debian.org/status/fetch.php?pkg=spglib&arch=arm64&ver=1.11.2-2&stamp=1544190459&raw=0), [i386](https://buildd.debian.org/status/fetch.php?pkg=spglib&arch=i386&ver=1.11.2-2&stamp=1544194416&raw=0), [ppc64el](https://buildd.debian.org/status/fetch.php?pkg=spglib&arch=ppc64el&ver=1.11.2-2&stamp=1544190307&raw=0), [s390x](https://buildd.debian.org/status/fetch.php?pkg=spglib&arch=s390x&ver=1.11.2-2&stamp=1544190423&raw=0), [hurd-i386](https://buildd.debian.org/status/fetch.php?pkg=spglib&arch=hurd-i386&ver=1.11.2-2&stamp=1544190461&raw=0), [kfreebsd-i386](https://buildd.debian.org/status/fetch.php?pkg=spglib&arch=kfreebsd-i386&ver=1.11.2-2&stamp=1544204965&raw=0) and [riscv64](https://buildd.debian.org/status/fetch.php?pkg=spglib&arch=riscv64&ver=1.11.2-2&stamp=1544196507&raw=0) architectures (please see links for extended failure logs). The following input files seem to cause the failures:
* python/test/data/orthorhombic/POSCAR-045-2
* python/test/data/cubic/POSCAR-196-2
* python/test/data/cubic/POSCAR-225-2

Can this be caused by floating point math problems? If so, is there a way to make tests less sensitive to it?

**Comment by atztogo** [comment]
Thanks for your useful check. I think, your guess is correct on floating point math problems. But I must say that the test on AMD64 went OK by luck. 

The Wyckoff letters were swapped by the choice of origin by centring, for example,
No. 45 Iba2 a<-->b
No. 196 F23 g<-->f
No. 225 Fm-3m a<-->b
In the current spglib, the choice of these origins can be found randomly, therefore the equivalent Wyckoff positions are interchanged. We in spglib don't have a standardization way to specifically choose one of equivalent Wyckoff positions. So the test should be written to pass for equivalent Wyckoff positions. I will write a better test but need sometime to have a good idea to achieve it.

Meanwhile, can you stop this test? Or do I release another version for it? Which is better in terms of semantic versioning?

If you stop it, at https://github.com/atztogo/spglib/blob/996d636f5d19a4b7656e59be1943b94dfb515391/python/test/test_spglib.py#L98
please comment out the following four lines:
```
            wyckoffs = dataset['wyckoffs']
            wyckoffs_ref = yaml.load(open(reffname))['wyckoffs']
            for w, w_ref in zip(wyckoffs, wyckoffs_ref):
                self.assertEqual(w, w_ref, msg=("%s" % fname))
```

Thanks for taking your time!

**Comment by merkys** [comment]
> In the current spglib, the choice of these origins can be found randomly, therefore the equivalent Wyckoff positions are interchanged. We in spglib don't have a standardization way to specifically choose one of equivalent Wyckoff positions. So the test should be written to pass for equivalent Wyckoff positions. I will write a better test but need sometime to have a good idea to achieve it.

Could there be an option implemented to fix the choice of origin? Using it the user (and this test) could expect the deterministic result.

> Meanwhile, can you stop this test? Or do I release another version for it? Which is better in terms of semantic versioning?

I will comment out the test in Debian package to make it built successfully, just as you have pointed out. As this issue is not crucial, I think there is no hurry to release another version for now.

Many thanks for prompt reply!

**Comment by jochym** [comment]
If I may include my opinion: It is important to have deterministic results. "By accident" results often bite users and packagers - they tend to change with architecture or toolchain. I would suggest using explicitly deterministic solution or, if the physics is not deterministic/unique, including non-uniqueness in the result explicitely (e.g. as a sorted list or other stable data structure). 
BTW: I wonder how it passed multi-arch tests in the conda-forge pipeline? Is the test included in standard setup I am using for c-f?

**Comment by atztogo** [comment]
To make more deterministic is rather a research than just an implementation, e.g. http://scripts.iucr.org/cgi-bin/paper?S010876730302186X. It is too much job for me. But the release v1.11.x was my challenge to make it more deterministic than before at one part, which required nontrivial effort that nobody knows.

@merkys's test failed on different CPU architectures. Maybe @jochym's test ran on only x86-64.

**Comment by merkys** [comment]
@atztogo I've got the feeling of the problem. One way of dealing with non-determinism is always taking the same origin. Another way is producing all equivalent result sets and letting the receiver choose. Of course this might be problematic due to combinatorial explosion. Interchanging of Wyckoff positions is peculiar, but it would be very useful (IMO) to have it.

**Comment by atztogo** [comment]
Because the same discussion is applied to Euclidean/affine normalizer, this issue has to be solved together with it. To solve the issue you raise needs a lot of time to work. But unfortunately I don't have time now. So I will put this on my to-do list in the future. What should be done in my mind is:

- [ ] Creation of Euclidean normalizer dataset and providing API to obtain the standardized crystal structures against its generators (including translation of lattice points in conventional unit cell)
- [ ] Comparison of lengths and angles will be written more strictly like http://scripts.iucr.org/cgi-bin/paper?S010876730302186X. At least, Delaunay reduction in spglib should be written in this way.

The former needs the knowledge of mathematical treatment of matrix representations of space group operations in crystallography knowing its (many) convention. The later would be done better by informatics specialist.

**Comment by atztogo** [comment]
@merkys, I worked on this issue from numerical treatment related to different machine precision. What I have tested is only between Ubuntu 64bit and 32bit, and macOS 64bit. Against these, the all tests passed. However there may be systems where the tests will not pass. At least I want to expect spglib works for 32 and 64 bit systems with typical symmetry tolerance = 1e-5. So can I ask you to test for debian with different hardwares as what you did? Currently the updated code is in `precision-test` branch.

**Comment by merkys** [comment]
Happy to see the progress with this issue. I have never tried building unreleased code on Debian hardware farm (it's a bit more complicated as I don't have direct access yet), but I'll see what I can do with it.

**Comment by merkys** [comment]
I have run the tests, however, problems on most of the architectures seem to persist: https://buildd.debian.org/status/package.php?p=spglib&suite=experimental

**Comment by atztogo** [comment]
Very useful information. Thanks!

**Comment by atztogo** [comment]
@merkys, I also made additional tuning of spglib. Can I ask to test again the `precision-test` branch (920d01ce439d37c173768f610c92ed3f4f9b5941)? It is not easy to write this improvement because I don't have architectures where I can test. Especiall I don't have any idea what happened for mips. Other architectures, I touched the spglib code where I can guess because the failures happened for virtual structures, which implied the tiny difference of lengths of basis vectors can cause the problem. I can't expect any way to make them perfect, but your help is very helpful to make spglib better.

**Comment by merkys** [comment]
@atztogo, I will rerun the test build ASAP. I assume that in the most architectures tests fail due to the lack of precision in floating point handling. This probably isn't a serious issue, it's just that certain cell conditions will yield different results on different architectures.

Build process on MIPS seems to have failed due to computation taking too long during test case ``test_std_symmetry``. However, [this used to pass before on mips](https://buildd.debian.org/status/fetch.php?pkg=spglib&arch=mips&ver=1.11.2-3&stamp=1544980524&raw=0), so it might be a temporary issue on MIPS builder.

**Comment by atztogo** [comment]
@merkys, what I fixed was one of them as you wrote, which check perpendicular condition if the inner product is larger than 0 or not. Please take your time but indeed your test is helpful. Thanks.

**Comment by merkys** [comment]
@atztogo, I have reuploaded the version you indicated today. You may use the old link to access the build matrix: https://buildd.debian.org/status/package.php?p=spglib&suite=experimental. The slowest builders might take three or more days to complete (``Needs-Build`` means that build process is queued on the machine).

**Comment by atztogo** [comment]
@merkys, it seems the results are better than before, but some tests have not ended yet. One reason is one of the tests is heavy. Do you think it's better to remove the test?

To all, I plan to release next version before v2.0. I can't judge if this Wyckoff position issue is solved or not considering the comments here, but I think it is more important to release than to solve this issue because this issue is not really the problem in a sense of space group but the choice.

**Comment by merkys** [comment]
@atztogo, indeed build process is now smooth on all architectures except mips. This is a minor trouble: if it won't build, I will instruct mips builder to skip this test case. There is no need to remove the test now.

**Comment by atztogo** [comment]
Thanks. Merged to master and released as v1.12.0.

**Comment by merkys** [comment]
Thanks, @atztogo!

**Comment by merkys** [comment]
By the way, v1.12.0 built successfully on mips (https://buildd.debian.org/status/package.php?p=spglib). Seemingly non-experimental builds are given more time to complete.
